### PR TITLE
Hotfix: Run all tests serially in the current process

### PR DESCRIPTION
**Pull request by craigcoles**
# Overview

* Runs the tests using the `--runInBand` flag to allow tests to be run serially in the current process.

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Code complete
- [ ] Changeset

### CODE REVIEW

**Comment by benjaminreid** [comment]
Does this allow them to run with turbo from the root now and get them all to pass?

**Comment by craigcoles** [comment]
@benjaminreid This actually just allows for the tests to all be run in unison whether its just running the batch of Open Format SDK, React SDK or both together.

**Comment by craigcoles** [comment]
Running tests on the Open Format

## Without `--runInBand`

```shell
Test Suites: 4 failed, 5 passed, 9 total
Tests:       10 failed, 24 passed, 34 total
Snapshots:   0 total
Time:        19.781 s, estimated 25 s
Ran all test suites.
```

## With `--runInBand`

```bash
Test Suites: 9 passed, 9 total
Tests:       34 passed, 34 total
Snapshots:   0 total
Time:        44.73 s, estimated 93 s
Ran all test suites.
```

**Comment by benjaminreid** [comment]
Does the normally SDK require it too? This is a bit of a band aid as it does slow the tests down quite a lot. Merge it if it required there too.

**Pull request merged**
